import 'package:flutter/material.dart';

class ReportsScreen extends StatelessWidget {
  final Map<String, dynamic>? scanData;
  const ReportsScreen({super.key, this.scanData});

  @override
  Widget build(BuildContext context) {
    if (scanData == null) {
      return const Center(child: Text("No data to report on. Import a CSV first.", style: TextStyle(color: Color(0xFFA1A1AA))));
    }

    final aiReport = scanData!['ai_report'] as Map<String, dynamic>? ?? {};
    final isAi = aiReport['is_ai'] == true;
    final totalInvested = (scanData!['total_invested'] as num?)?.toDouble() ?? 0.0;
    final currentValue = (scanData!['current_value'] as num?)?.toDouble() ?? 0.0;
    final pnl = (scanData!['pnl'] as num?)?.toDouble() ?? 0.0;
    final pnlPct = (scanData!['pnl_percentage'] as num?)?.toDouble() ?? 0.0;
    final num healthScore = scanData!['health_score'] as num? ?? 0;
    final healthStatus = scanData!['health_status']?.toString() ?? 'Unknown';

    final profitContributors = aiReport['profit_contributors'] as List? ?? [];
    final lossContributors = aiReport['loss_contributors'] as List? ?? [];
    final marketContext = aiReport['market_context'] as List? ?? [];
    final risks = aiReport['risks'] as List? ?? [];
    final strengths = List<String>.from(aiReport['strengths'] ?? []);
    final concerns = List<String>.from(aiReport['concerns'] ?? []);
    final monitorNext = aiReport['monitor_next'] as List? ?? [];
    final priorities = aiReport['research_priorities'] as List? ?? [];
    final investorQuestions = List<String>.from(aiReport['investor_questions'] ?? []);

    return SingleChildScrollView(
      padding: const EdgeInsets.all(32.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Text('Portfolio Intelligence Report', style: TextStyle(color: Colors.white, fontSize: 28, fontWeight: FontWeight.bold)),
              if (isAi)
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                  decoration: BoxDecoration(color: const Color(0xFF4F46E5).withOpacity(0.1), borderRadius: BorderRadius.circular(16)),
                  child: const Text("Generated by Local AI", style: TextStyle(color: Color(0xFF818CF8), fontWeight: FontWeight.bold, fontSize: 12)),
                )
              else
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                  decoration: BoxDecoration(color: const Color(0xFFEF4444).withOpacity(0.1), borderRadius: BorderRadius.circular(16)),
                  child: const Text("Fallback / Local Only", style: TextStyle(color: Color(0xFFEF4444), fontWeight: FontWeight.bold, fontSize: 12)),
                )
            ],
          ),
          const SizedBox(height: 32),

          // A. EXECUTIVE ASSESSMENT & B. PERFORMANCE SNAPSHOT
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Expanded(
                flex: 2,
                child: _buildCard('Executive Assessment', Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(aiReport['executive_assessment']?.toString() ?? "No executive assessment available.", style: const TextStyle(color: Color(0xFFA1A1AA), fontSize: 15, height: 1.6)),
                    const SizedBox(height: 16),
                    const Divider(color: Color(0xFF2A2A2A)),
                    const SizedBox(height: 16),
                    const Text('Why am I making / losing money?', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
                    const SizedBox(height: 8),
                    Text(aiReport['performance_explanation']?.toString() ?? "No explanation available.", style: const TextStyle(color: Color(0xFFA1A1AA), fontSize: 14, height: 1.5)),
                  ]
                )),
              ),
              const SizedBox(width: 24),
              Expanded(
                flex: 1,
                child: _buildCard('Performance Snapshot', Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _buildSnapshotRow('Health Score', '$healthScore / 100', color: const Color(0xFF22C55E)),
                    _buildSnapshotRow('Health Status', healthStatus),
                    const Divider(color: Color(0xFF2A2A2A), height: 32),
                    _buildSnapshotRow('Total Investment', '₹${totalInvested.toStringAsFixed(2)}'),
                    _buildSnapshotRow('Current Value', '₹${currentValue.toStringAsFixed(2)}'),
                    _buildSnapshotRow('Unrealized P&L', '${pnl >= 0 ? '+' : ''}₹${pnl.abs().toStringAsFixed(2)}', color: pnl >= 0 ? const Color(0xFF22C55E) : const Color(0xFFEF4444)),
                    _buildSnapshotRow('P&L %', '${pnlPct >= 0 ? '+' : ''}${pnlPct.toStringAsFixed(2)}%', color: pnl >= 0 ? const Color(0xFF22C55E) : const Color(0xFFEF4444)),
                  ]
                )),
              ),
            ],
          ),
          const SizedBox(height: 24),

          // C/D/E. PERFORMANCE DRIVERS (Contributors)
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Expanded(
                child: _buildCard('Profit Contributors', Column(
                  children: profitContributors.isEmpty ? [const Text("None identified.", style: TextStyle(color: Color(0xFFA1A1AA)))] : 
                  profitContributors.map((c) => _buildDriverItem(c, const Color(0xFF22C55E))).toList()
                ))
              ),
              const SizedBox(width: 24),
              Expanded(
                child: _buildCard('Loss Contributors', Column(
                  children: lossContributors.isEmpty ? [const Text("None identified.", style: TextStyle(color: Color(0xFFA1A1AA)))] : 
                  lossContributors.map((c) => _buildDriverItem(c, const Color(0xFFEF4444))).toList()
                ))
              ),
            ],
          ),
          const SizedBox(height: 24),

          // F/G. CONCENTRATION & SECTOR RISK
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Expanded(
                child: _buildCard('Concentration Risk', Text(
                  aiReport['concentration_analysis']?.toString() ?? "No concentration analysis.",
                  style: const TextStyle(color: Color(0xFFA1A1AA), height: 1.5)
                ))
              ),
              const SizedBox(width: 24),
              Expanded(
                child: _buildCard('Sector Analysis', Text(
                  aiReport['sector_analysis_text']?.toString() ?? "No sector analysis.",
                  style: const TextStyle(color: Color(0xFFA1A1AA), height: 1.5)
                ))
              ),
            ],
          ),
          const SizedBox(height: 24),

          // H. MARKET CONTEXT
          _buildCard('Market Context & Evidence', Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: marketContext.isEmpty ? [const Text("No relevant public evidence found.", style: TextStyle(color: Color(0xFFA1A1AA)))] : 
            marketContext.map((ctx) => Container(
              margin: const EdgeInsets.only(bottom: 16),
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(color: const Color(0xFF161616), borderRadius: BorderRadius.circular(12), border: Border.all(color: const Color(0xFF2A2A2A))),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text(ctx['ticker']?.toString() ?? "", style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
                      Text(ctx['date']?.toString() ?? "", style: const TextStyle(color: Color(0xFFA1A1AA), fontSize: 12)),
                    ],
                  ),
                  const SizedBox(height: 8),
                  Text(ctx['headline']?.toString() ?? "", style: const TextStyle(color: Color(0xFF818CF8), fontWeight: FontWeight.w600)),
                  const SizedBox(height: 4),
                  Text("Source: ${ctx['source']}", style: const TextStyle(color: Color(0xFFA1A1AA), fontSize: 12)),
                  const SizedBox(height: 12),
                  const Text("Potential Impact:", style: TextStyle(color: Colors.white, fontSize: 12, fontWeight: FontWeight.bold)),
                  const SizedBox(height: 4),
                  Text(ctx['impact']?.toString() ?? "", style: const TextStyle(color: Color(0xFFA1A1AA), fontSize: 13, height: 1.5)),
                ],
              ),
            )).toList()
          )),
          const SizedBox(height: 24),

          // J. RISK ANALYSIS & K/L. STRENGTHS / CONCERNS
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Expanded(
                child: _buildCard('Identified Risks', Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: risks.isEmpty ? [const Text("No specific risks identified.", style: TextStyle(color: Color(0xFFA1A1AA)))] : 
                  risks.map((r) => Padding(
                    padding: const EdgeInsets.only(bottom: 12),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(r['type']?.toString() ?? "", style: const TextStyle(color: Color(0xFFF59E0B), fontWeight: FontWeight.bold)),
                        const SizedBox(height: 2),
                        Text(r['description']?.toString() ?? "", style: const TextStyle(color: Color(0xFFA1A1AA), fontSize: 13, height: 1.4)),
                      ],
                    ),
                  )).toList()
                ))
              ),
              const SizedBox(width: 24),
              Expanded(
                child: _buildCard('Strengths & Concerns', Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text('Strengths:', style: TextStyle(color: Color(0xFF22C55E), fontWeight: FontWeight.bold)),
                    const SizedBox(height: 8),
                    ...strengths.map((item) => Padding(padding: const EdgeInsets.only(bottom: 4), child: Text('• $item', style: const TextStyle(color: Color(0xFFA1A1AA))))),
                    const SizedBox(height: 16),
                    const Text('Areas of Concern:', style: TextStyle(color: Color(0xFFEF4444), fontWeight: FontWeight.bold)),
                    const SizedBox(height: 8),
                    ...concerns.map((item) => Padding(padding: const EdgeInsets.only(bottom: 4), child: Text('• $item', style: const TextStyle(color: Color(0xFFA1A1AA))))),
                  ],
                ))
              ),
            ],
          ),
          const SizedBox(height: 24),

          // M/N. WATCHLIST & INVESTOR ACTION
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Expanded(
                child: _buildCard('What To Watch Next', Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: monitorNext.isEmpty ? priorities.map((p) => _buildPriorityItem(p)).toList() : 
                  monitorNext.map((m) => Padding(
                    padding: const EdgeInsets.only(bottom: 12),
                    child: Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Container(
                          padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                          decoration: BoxDecoration(color: const Color(0xFF374151), borderRadius: BorderRadius.circular(4)),
                          child: Text(m['holding']?.toString() ?? "", style: const TextStyle(color: Colors.white, fontSize: 12, fontWeight: FontWeight.bold)),
                        ),
                        const SizedBox(width: 12),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(m['priority']?.toString() ?? "Monitor", style: const TextStyle(color: Color(0xFFF59E0B), fontSize: 12, fontWeight: FontWeight.bold)),
                              Text(m['reason']?.toString() ?? "", style: const TextStyle(color: Color(0xFFA1A1AA), fontSize: 13)),
                            ],
                          ),
                        )
                      ],
                    ),
                  )).toList()
                ))
              ),
              const SizedBox(width: 24),
              Expanded(
                child: _buildCard('Investor Action Framework', Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text("Questions to investigate based on this portfolio:", style: TextStyle(color: Colors.white, fontWeight: FontWeight.w600, fontSize: 14)),
                    const SizedBox(height: 12),
                    ...investorQuestions.map((q) => Padding(
                      padding: const EdgeInsets.only(bottom: 8),
                      child: Row(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const Icon(Icons.help_outline, color: Color(0xFF818CF8), size: 16),
                          const SizedBox(width: 8),
                          Expanded(child: Text(q, style: const TextStyle(color: Color(0xFFA1A1AA), height: 1.4))),
                        ],
                      ),
                    ))
                  ],
                ))
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildCard(String title, Widget child) {
    return Container(
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(color: const Color(0xFF1E1E1E), borderRadius: BorderRadius.circular(16), border: Border.all(color: const Color(0xFF2A2A2A))),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title, style: const TextStyle(color: Colors.white, fontSize: 16, fontWeight: FontWeight.bold)),
          const SizedBox(height: 16),
          child,
        ],
      ),
    );
  }

  Widget _buildSnapshotRow(String label, String value, {Color color = Colors.white}) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 6.0),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(label, style: const TextStyle(color: Color(0xFFA1A1AA))),
          Text(value, style: TextStyle(color: color, fontWeight: FontWeight.bold, fontSize: 15)),
        ],
      ),
    );
  }

  Widget _buildDriverItem(dynamic item, Color color) {
    if (item is! Map) return const SizedBox();
    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(color: const Color(0xFF161616), borderRadius: BorderRadius.circular(8)),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(Icons.show_chart, color: color, size: 20),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(item['holding']?.toString() ?? 'Unknown', style: TextStyle(color: color, fontWeight: FontWeight.bold)),
                const SizedBox(height: 4),
                Text(item['reason']?.toString() ?? '', style: const TextStyle(color: Color(0xFFA1A1AA), fontSize: 13, height: 1.4)),
              ],
            ),
          )
        ],
      ),
    );
  }

  Widget _buildPriorityItem(dynamic p) {
    if (p is! Map) return const SizedBox();
    String priority = p['level']?.toString() ?? 'Low';
    Color badgeColor = priority == 'High' ? Colors.red : (priority == 'Medium' ? Colors.orange : Colors.green);
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4.0),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(p['company']?.toString() ?? '', style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
            decoration: BoxDecoration(color: badgeColor.withOpacity(0.1), borderRadius: BorderRadius.circular(12), border: Border.all(color: badgeColor)),
            child: Text(priority, style: TextStyle(color: badgeColor, fontSize: 12)),
          ),
        ],
      ),
    );
  }
}
